FROM debian:stable-slim
RUN set -eux;\
    apt-get update;\
    apt-get install -y --no-install-recommends polipo;\
    apt-get clean; rm -rf /var/lib/apt/lists/*;

VOLUME      ["/var/cache/polipo"]
EXPOSE 8123
CMD polipo proxyAddress=:: disableIndexing=false
