FROM    alpine
RUN set -eux;\
    apk update;\
    apk --no-cache add dnsmasq;\
    rm -rf /tmp/* /var/cache/apk/*  /var/tmp/*;\
    echo DONE
RUN set -eux;\
    echo 'no-resolv'>/etc/dnsmasq.conf;\
    echo 'log-queries'>>/etc/dnsmasq.conf;\
    echo 'server=8.8.8.8'>>/etc/dnsmasq.conf;\
    echo 'server=208.67.222.222'>>/etc/dnsmasq.conf;\
    echo DONE
EXPOSE  53/udp