FROM        ubuntu
RUN set -eux;\
    export http_proxy=$HTTP_PROXY; \
    apt-get update;\
    apt-get install -y python3 python3-pip;\
    apt-get clean; rm -rf /var/lib/apt/lists/*;\
    echo DONE

RUN set -eux;\
    pip3 install awscli --upgrade;\
    echo DONE
