FROM ubuntu
RUN set -eux;\
    export http_proxy=$HTTP_PROXY; \
    apt-get update;\
    env DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -yq \
 debootstrap \
 libguestfs-tools \
 linux-image-generic \
 qemu-utils \
 ;apt-get clean; rm -rf /var/lib/apt/lists/*;

