FROM        ubuntu
RUN set -eux;\
    export http_proxy=$HTTP_PROXY; \
    apt-get update;\
    apt-get install -y python3 python3-pip;\
    apt-get clean; rm -rf /var/lib/apt/lists/*;\
    echo DONE

RUN set -eux;\
    pip3 install awscli --upgrade;\
    echo DONE

ARG userid
ARG groupid
ARG username
COPY entrypoint.sh /root/
RUN set -eux; \
    groupadd -g $groupid $username; \
    useradd -m -u $userid -g $groupid $username; \
    usermod -aG sudo $username; \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers; \
    echo $username >/root/username; \
    echo DONE
ENTRYPOINT ["/root/entrypoint.sh"]
CMD ["run", "bash", "-l"]
