#!/bin/bash
set -eux

cleanup () {
    gcloud compute instances list --uri|awk -F / '{print $11}'|xargs --no-run-if-empty -n 1 gcloud --verbosity info compute instances delete --quiet
}
cleanup
echo trap cleanup EXIT
echo --machine-type f1-micro
gcloud --verbosity info compute instances create --image-project ubuntu-os-cloud  --image-family ubuntu-minimal-1804-lts --boot-disk-size=10GB --custom-cpu=1 --custom-memory=1024MB test
echo gcloud compute instances describe test
for t in $(seq -s ' ' 1 10); do
   if gcloud compute ssh test -- id ; then
       break
   fi
   sleep 5
done
gcloud compute instances attach-disk test --disk=mirror
gcloud compute ssh test -- sudo bash <<"_EOF_"
set -eux
dd if=/dev/zero of=/swapfile bs=1M count=512
mkswap /swapfile
chmod 0600 /swapfile
swapon -f /swapfile
apt-get update
apt-get install -y --no-install-recommends apt-utils
apt-get install -y --no-install-recommends \
 docker.io\
 git-core\
 less\
 make\
 sysstat\
 vim-tiny\
;
usermod -aG docker $SUDO_USER
mkfs.ext4 -m 0 -F  -O ^has_journal   /dev/sdb
mkdir -p /data
mount /dev/sdb /data
_EOF_
gcloud compute ssh test -- bash <<_EOF_
set -eux
git clone https://github.com/TheCBaH/aosp-builder.git
cd aosp-builder
git config --global user.name $USER
git config --global user.email "$USER@gmail.com"
make user
make volumes
sudo mkdir -p /data/aosp/aosp_mirror-master
make mirror.master SYNC_JOBS=1
_EOF_
gcloud compute ssh test -- sudo bash <<_EOF_
set -eux
sudo umount /data
_EOF_
gcloud compute instances detach-disk test --disk=mirror
gcloud compute ssh test -- sudo dd if=/dev/sda of=/dev/null bs=1M count=1024
gcloud compute ssh test -- lsblk -m
echo gcloud --verbosity info compute instances stop test
