name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [16.04, 18.04, 20.04]
        os: [ubuntu]
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: kvm.image
      run: |
        set -x
        make -C docker_kvm kvm_image
        make -C docker_kvm ${{ matrix.os }}-${{ matrix.version }}.init
    - name: docker
      run: |
        make USE_TAP=y ${{ matrix.os }}-${{ matrix.version }}.docker_test
  images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make polipo.container
    - run: make http_proxy="http://$(hostname -I|cut -d' ' -f1):8123" apt_cache.container
    - run: make http_proxy="http://$(hostname -I|cut -d' ' -f1):8123" dnsmasq.image
    - run: make http_proxy="http://$(hostname -I|cut -d' ' -f1):8123" debootstrap.init
    - run: make http_proxy="http://$(hostname -I|cut -d' ' -f1):8123" gcloud.image
    - run: make http_proxy="http://$(hostname -I|cut -d' ' -f1):8123" tensorflow.image
    - run: make http_proxy="http://$(hostname -I|cut -d' ' -f1):8123" pytorch.image
    - run: make http_proxy="http://$(hostname -I|cut -d' ' -f1):8123" softether.image
    - run: make -C ceph http_proxy="http://$(hostname -I|cut -d' ' -f1):8123" ceph-admin.image
